Repository acm-ucr/leap-website, pull requests merged in 2025-01, with the labels that each got.

#28 footer
  package-lock.json
  package.json
  src/components/Footer.tsx
  src/data/footer.tsx
  src/public/ucr_leap_logo.svg
  tsconfig.json
Labels: ready for review, changes requested

#26 FAQCards
  src/components/about/About.tsx
  src/components/about/FAQCard.tsx
Labels: help wanted, changes requested

#25 Add Value Boxes Component for Home Section
  src/components/home/Value_Box.tsx
Labels: ready for review, changes requested

#57 navbar init
  src/components/Navbar.tsx
  src/data/navbar.tsx
Labels: ready for review

#56 ShreyGK6/Description_Component
  public/assets/home/description.webp
  src/app/page.tsx
  src/components/home/Description.tsx
  src/components/home/Description_Component.tsx
  src/components/home/Value_Box.tsx
  tsconfig.json
Labels: ready for review, changes requested

#58 Kevinloritsch/minor fixes
  public/assets/ucr_leap_logo.webp
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/Navbar.tsx
  src/components/home/Description.tsx
  src/components/home/Description_Component.tsx
  src/components/home/Value_Box.tsx
Labels: ready for review

#68 Issue with pulling from dev on old branch
  src/app/events/page.tsx
  src/components/events/Events.tsx
  src/data/events.tsx
Labels: ready for review
