Repository acm-ucr/leap-website, pull requests merged in 2025-02, with the labels that each got.

#71 added the background to Leap
  public/assets/about/background.webp
  src/components/about/Leap.tsx
Labels: ready for review

#63 Created BoardCard Component
  src/components/board/BoardCard.tsx
Labels: ready for review

#70 Carousel Added
  components.json
  package-lock.json
  package.json
  src/app/globals.css
  src/components/Carousel.tsx
  src/components/gallery/Gallery.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/data/gallery.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: enhancement, ready for review

#48 Ctraino/headercomponent
  src/app/board/page.tsx
  src/app/events/page.tsx
  src/components/board/header.tsx
Labels: ready for review

#61 added more FAQCard
  public/assets/about/bg-about-questions.png
  src/components/about/About.tsx
  src/components/about/faqData.tsx
  src/components/about/question.tsx
Labels: ready for review

#81 Derrick mao/home page
  public/assets/about/bg-about-questions.png
  public/assets/about/bg-about-questions.webp
  public/assets/home/descriptionBg.svg
  public/assets/home/header.webp
  src/app/page.tsx
  src/components/about/question.tsx
  src/components/home/Description_Component.tsx
  src/components/home/Header.tsx
Labels: ready for review

#30 recloned and added code
  src/components/about/About.tsx
  src/components/about/ValueCard.tsx
Labels: ready for review

#35 Title Component
  src/components/ui/Title.tsx
Labels: ready for review

#88 Upcoming Title Component
  src/app/events/page.tsx
  src/components/events/UpcomingTitle.tsx
Labels: ready for review

#50 Home Page Text & Formatting
  src/app/page.tsx
  src/components/homepage/Description_Component.tsx
Labels: ready for review

#93 responsive FQA card
  src/components/about/FAQCard.tsx
  src/components/about/question.tsx
Labels: responsive

#106 Responsive Footer
  src/components/Footer.tsx
Labels: ready for review

#101 backgrounds of headers
  public/assets/header-background-about.webp
  public/assets/header-background-board.webp
  src/app/about/page.tsx
  src/app/board/page.tsx
  src/app/events/page.tsx
  src/components/Header.tsx
  src/components/board/header.tsx
Labels: ready for review

#64 Gallery Mapped
  public/gallery/grid/grid15.webp
  src/app/gallery/page.tsx
  src/components/gallery/Gallery.tsx
  src/components/gallery/PicturesData.tsx
  src/components/gallery/PicturesGrid.tsx
Labels: ready for review

#109 Andres Lopez / Mobile Responsiveness Event Component
  src/components/events/Events.tsx
Labels: ready for review, responsive

#103 About Page Description Component Responsify
  src/components/about/Leap.tsx
Labels: ready for review, responsive

#117 Animated Gallery
  package-lock.json
  package.json
  src/components/gallery/Gallery.tsx
  src/components/gallery/PicturesGrid.tsx
Labels: ready for review, animation

#119 Home Page Photo and Value Box Responsify
  src/components/home/Description.tsx
  src/components/home/Value_Box.tsx
  src/components/home/ValuesContainer.tsx
Labels: ready for review, responsive

#121 Values Section
  public/assets/about/bg-Value-about.webp
  public/assets/about/bg-about-us.webp
  src/app/about/page.tsx
  src/components/about/About.tsx
  src/components/about/FAQCard.tsx
  src/components/about/ValueCard.tsx
  src/components/about/ValueSection.tsx
  src/components/about/question.tsx
  src/data/ValueData.tsx
  src/data/faqData.tsx
Labels: changes requested

#132 Animated Recruitment Questions
  src/components/about/FAQCard.tsx
  src/components/about/question.tsx
  src/data/faqData.tsx
Labels: ready for review

#140 Andres Lopez / Updated NavBar to use usepathname.
  src/components/Navbar.tsx
Labels: ready for review

#130 Andres Lopez / Animated About Us Component
  package-lock.json
  package.json
  src/components/about/Leap.tsx
Labels: ready for review, changes requested, animation

#131 Derrick mao/home
  public/assets/home/header.webp
  public/assets/home/valuesBg.svg
  src/app/page.tsx
  src/components/home/CoreValues.tsx
  src/components/home/Header.tsx
  src/components/home/ValuesContainer.tsx
Labels: question, responsive

#135 Animate404
  src/app/not-found.tsx
Labels: changes requested, animation

#151 Gallery header
  src/components/gallery/GalleryWrapper.tsx
Labels: ready for review

#136 experiemting with header width bug
  src/app/events/page.tsx
  src/components/Header.tsx
Labels: animation

#161 added background for about header
  src/app/about/page.tsx
  src/components/Header.tsx
  src/components/about/Button.tsx
Labels: ready for review

#162 Gallery Clean Up
  src/components/gallery/GalleryWrapper.tsx
  src/components/gallery/PicturesGrid.tsx
Labels: ready for review

#168 Button Consistency
  src/app/not-found.tsx
  src/components/Button.tsx
Labels: ready for review

#170 added images for carousel
  src/components/gallery/Carousel.tsx
  src/data/GalleryData.ts
Labels: ready for review

#139 Animated board card
  src/app/board/page.tsx
  src/components/board/BoardMemberCards.tsx
  src/components/board/BoardWrapper.tsx
  src/data/BoardData.tsx
Labels: ready for review, animation
