Repository acm-ucr/leap-website, pull requests merged in 2025-03, with the labels that each got.

#153 Andres Lopez / Animated Core Value cards and flowers image.
  src/components/home/ValueBox.tsx
  src/components/home/ValuesContainer.tsx
Labels: ready for review, animation

#169 Added animations for home component
  package-lock.json
  src/components/home/Header.tsx
Labels: changes requested, animation

#173 Navbar Clean Up
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/about/FAQSection.tsx
  src/data/FooterData.tsx
  tailwind.config.ts
Labels: ready for review

#163 motion to values
  package-lock.json
  package.json
  src/components/about/FAQCard.tsx
  src/components/about/ValueCard.tsx
  src/components/about/ValueSection.tsx
  src/data/ValueData.ts
Labels: changes requested

#185 Fixed mobile navbar component, seems like color was already changed
  src/components/Navbar.tsx
Labels: ready for review

#182 about FAQ stagger motion
  src/components/about/FAQSection.tsx
Labels: ready for review, animation

#186 constitution icon
  src/components/Footer.tsx
  src/data/FooterData.tsx
Labels: changes requested

#178 Andres Lopez / Added animation to the Events Header and Subtext.
  src/components/Header.tsx
Labels: ready for review, animation

#181 Added Carousel Arrows
  src/components/gallery/Carousel.tsx
  src/components/gallery/GalleryWrapper.tsx
Labels: ready for review

#191 cleaned up board cards
  src/components/board/BoardMemberCards.tsx
  src/components/board/BoardWrapper.tsx
Labels: ready for review

#190 calendar (new PR)
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/components/Footer.tsx
  src/components/events/Calendar.tsx
  src/components/events/Events.tsx
  src/components/events/UpcomingTitle.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  src/data/EventsData.ts
  tailwind.config.ts
Labels: ready for review

#203 Ctraino/boardcardanimation
  src/components/board/BoardWrapper.tsx
Labels: animation

#205 no upcoming events text
  src/components/events/Calendar.tsx
  src/data/EventsData.ts
Labels: ready for review

#196 FAQ Card Cleanup
  src/components/about/FAQCard.tsx
  src/components/about/FAQSection.tsx
Labels: ready for review

#209 Calendar month spacing, animation, background
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/components/events/Calendar.tsx
  src/components/events/UpcomingTitle.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  tailwind.config.ts
Labels: ready for review

#208 Added board page assets
  src/app/board/page.tsx
  src/components/board/BoardDecorationsBottom.tsx
  src/components/board/BoardDecorationsTop.tsx
  src/components/board/BoardMemberCards.tsx
  src/components/board/BoardWrapper.tsx
Labels: ready for review, animation

#197 Andres Lopez / About Page Formatting
  package-lock.json
  src/app/about/page.tsx
  src/components/about/FAQSection.tsx
  src/components/about/Leap.tsx
  src/components/about/ValueSection.tsx
Labels: ready for review, changes requested

#202 navbar+footer fix
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/data/FooterData.tsx
Labels: changes requested

#217 Added Assets & Changed About Header
  src/app/about/page.tsx
  src/components/about/Leap.tsx
Labels: ready for review

#218 calendar mobile button bug
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
Labels: question

#219 Andres Lopez / Animated core values on homepage.
  src/components/home/CoreValues.tsx
Labels: ready for review, animation

#230 moved around
  src/components/home/Header.tsx
Labels: bug

#235 globals
  src/app/globals.css
  src/components/ui/calendar.tsx
Labels: bug

#237 small fixes
  package-lock.json
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/data/BoardData.tsx
Labels: ready for review
